'dev':
  'BACK_END_EXPLORER_URI': 'https://explorer-api-develop2.theaquaverse.io'
  'SSO_AQUAVERSE': 'https://sso-aquaverse-develop.theaquaverse.io'
  'scStaking': 'erd1qqqqqqqqqqqqqpgqnhuzesnpmel8npcpdh86yyhp6zzr573cnqjsh9uj78'
  'scClaim': 'erd1qqqqqqqqqqqqqpgqfha56cxr9hmyrqnw2mlthpcs2g20wzza4kns3drme3'
  'scLootbox': 'erd1qqqqqqqqqqqqqpgqprwcmex8jczqm88gvmzgqhsx23ev8nkmerqqyqzxa5'
  'URI_THALES': 'https://thales-api-develop.theaquaverse.io'
  'URI_STAKING_API': 'https://gateway-develop.theaquaverse.io/staking'
  'ROTG_TOKEN': 'ROTG-020900'
  'GUARDIAN_TOKEN': 'XGUARDIAN-abfbee'
  'LOOTBOXES_TOKEN': 'ALPHABOXES-8832e6'
  'TICKET_TOKEN': 'TICKET-bcd980'
  'ASSET_TOKEN': 'ASSET-6b7288'
'staging':
  'scClaim': 'erd1qqqqqqqqqqqqqpgqfha56cxr9hmyrqnw2mlthpcs2g20wzza4kns3drme3'
  'SSO_AQUAVERSE': 'https://sso-aquaverse-staging.theaquaverse.io'
  'BACK_END_EXPLORER_URI': 'https://explorer-api-develop2.theaquaverse.io'
  'scStaking': 'erd1qqqqqqqqqqqqqpgqc63k96c2ne6ywapq64sux60vw87fr47rnqjsgpr63q'
  'URI_THALES': 'https://thales-api-staging.theaquaverse.io'
  'URI_STAKING_API': 'https://gateway-develop.theaquaverse.io/staking'
  'ROTG_TOKEN': 'ROTG-fc7c99'
  'GUARDIAN_TOKEN': 'XGUARDIAN-abfbee'
  'LOOTBOXES_TOKEN': 'ALPHABOXES-8832e6'
'production':
  'BACK_END_EXPLORER_URI': 'https://explorer-api.theaquaverse.io'
  'SSO_AQUAVERSE': 'https://sso-aquaverse.theaquaverse.io'
  'scStaking': 'erd1qqqqqqqqqqqqqpgq3tnue9njnae6vznm7awgypmf78aw7gghmaqspp9hs0'
  'URI_THALES': 'https://thales-api.theaquaverse.io'
  'GUARDIAN_TOKEN': 'GUARDIAN-3d6635'
  'URI_STAKING_API': 'https://gateway.theaquaverse.io/staking'
